name: Image Server Container Release

on:
  push:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ImageServer/Dockerfile
          tags: ghcr.io/devinsightforge/imageserverservice:latest
          labels: |
            maintainer=${{ github.repository_owner }}
            repository=${{ github.repository }}
            commit_sha=${{ github.sha }}